name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWS }}
          server-dir: /323_323_lakota/wwwroot
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**